title = "PlayerMaid"  # From Git
gitRepoUrl = "https://github.com/arsonistd/PlayerMaid" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = ""

# From git:
organizationName = "ArsonistD"
projectName = "PlayerMaid"
url = "https://arsonistd.github.io"
baseUrl = "/PlayerMaid"
tagline = "Player wrapped garbage collector"

[navbar]
hideableSidebar = true

[footer]
style = "dark"

[footer.links]
title = ""
copyright = "Copyright © 2021 ArsonistD. Built with Moonwave and Docusaurus"

